"""citas sin hora especifica

Revision ID: 02da131a674e
Revises: 98eb17bab316
Create Date: 2026-07-20 01:00:39.324871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02da131a674e'
down_revision: Union[str, Sequence[str], None] = '98eb17bab316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'citas',
        sa.Column(
            'sin_hora_especifica',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column(
        'conversaciones',
        sa.Column(
            'sin_hora_especifica',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column('conversaciones', sa.Column('franja_preferida', sa.String(), nullable=True))
    op.add_column(
        'empresas',
        sa.Column(
            'permite_citas_sin_hora',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'permite_citas_sin_hora')
    op.drop_column('conversaciones', 'franja_preferida')
    op.drop_column('conversaciones', 'sin_hora_especifica')
    op.drop_column('citas', 'sin_hora_especifica')
    # ### end Alembic commands ###
